version: "3.8"
services:
  admin-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa-admin-ui
    restart: always
    environment:
      MEDUSA_ADMIN_BACKEND_URL: https://kilap-ecommerce-api.chroma-gaming.xyz
    ports:
      - "7001:80"
