version: "3.8"
services:
  ecommerce-admin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MEDUSA_ADMIN_BACKEND_URL: https://kilap-ecommerce-api.chroma-gaming.xyz
    container_name: ecommerce-admin
    restart: always
    ports:
      - "7001:80"
