name: ECommerce UI Release Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag version/name"
        required: true
      medusa_backend_url:
        description: "Fill the medusa host (backend)"
      host:
        description: "Fill the admin ui host"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
  LATEST_VERSION: latest
  MEDUSA_ADMIN_BACKEND_URL: ${{ vars.MEDUSA_ADMIN_BACKEND_URL }}
  HOST: ${{ vars.HOST }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup language version
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - name: Sanitize environment variables
        run: |
          echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> $GITHUB_ENV

      - name: Set output release tag by workflow_dispatch
        id: dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "RELEASE_VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Set output release tag by push
        id: push
        if: github.event_name == 'push'
        run: echo "RELEASE_VERSION=${{ github.event.head_commit.id }}" >> $GITHUB_ENV

      - name: Check and replace variable
        run: |
          if [ -z "${{ env.MEDUSA_ADMIN_BACKEND_URL }}" ]; then
            echo "MEDUSA_ADMIN_BACKEND_URL=${{ github.event.inputs.medusa_backend_url }}" >> $GITHUB_ENV
          fi
          if [ -z "${{ env.HOST }}" ]; then
            echo "HOST=${{ github.event.inputs.host }}" >> $GITHUB_ENV
          fi

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            MEDUSA_ADMIN_BACKEND_URL=${{ env.MEDUSA_ADMIN_BACKEND_URL }}
            HOST=${{ env.HOST }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.RELEASE_VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }}
